pull_request_rules:
  - name: Build and Merge Docker Image
    conditions:
      - and:
        - base=main
        - check-success=build
    actions:
      merge:
        method: fast-forward
        commit_message_template: |
        {{ title }} (#{{ number }})

        {{ body }}

        {% for user in approved_reviews_by %}
        Approved-By: {{user}}
        {% endfor %}
