pull_request_rules:
  - name: Continuous integration with Bors-like strategy
    conditions:
      - status-success=docker-build-success
      - base=main
    actions:
      merge:
        method: merge
