pull_request_rules:
  - name: automatic merge for main when CI passes.
    conditions:
      - base=main
      - status-success=github-actions/docker.yml
      - '#commits-behind>0'
    actions:
      merge:
        method: merge
