version: "3.7"

services:
  docusaurus:
    build:
      context: .
      target: development
    command: npm start
    ports:
      - 3000:3000
    volumes:
      - ./:/app
      - /app/node_modules