/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {

    SidebarNorteamericano: {
    'Norteamericano': ['API-Norteamericano/intro',
    'API-Norteamericano/obtener-access-token',
    'API-Norteamericano/inscripcion-usuario',
    'API-Norteamericano/desinscripcion-usuario',
    'API-Norteamericano/curso-proceso-relanzamiento',
    'API-Norteamericano/relanzamiento-curso'],
    },
    SidebarEOL: {
      'EOL': ['eol/intro',]
    },
    SidebarUAbierta: {
      'UAbierta': ['UAbierta/intro',]
    },
    SidebarVirtualLabX: {
      'VirtualLabX': ['VirtualLabX/intro',]
    },
    SidebarCMM: {
      'CMM Eduformación': ['CMM-Edu/intro',
      'CMM-Edu/obtener-access-token',
      'CMM-Edu/reporte-perfil-estudiante',
      'CMM-Edu/reporte-ora2',
      'CMM-Edu/reporte-problema',
      'CMM-Edu/reporte-roles-usuario',
      'CMM-Edu/lista-tareas']
    }

  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  // But you can create a sidebar manually

  // tutorialSidebar: [
  //   {
  //     type: 'category',
  //     label: 'Tutorial',
  //     items: ['hello'],
  //   },
  // ],
};

module.exports = sidebars;
