name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  merge_group:


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@main

    - name: Build the Docker image and Push to Github Container Registry
      run: |
        docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/docs-eol:${GITHUB_SHA}
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/eol-uchile/docs-eol:${GITHUB_SHA}
