name: Docker Image CI

on:
  pull_request:
    branches:
      - 'main'
  merge_group:
    types: [checks_requested]


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - uses: actions/checkout@main

    - name: Check out the PR branch
      if: github.event_name == 'pull_request'
      run: git checkout -B ${{ github.event.pull_request.head.ref }} ${{ github.event.pull_request.head.sha }}

    - name: Build the Docker image and Push to Github Container Registry
      run: |
        docker build . --file ./Dockerfile --tag ghcr.io/eol-uchile/docs-eol:${GITHUB_SHA}
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
        docker push ghcr.io/eol-uchile/docs-eol:${GITHUB_SHA}
